### ISSUE TITLE
Chromium downloader bad zip error

### ISSUE THREAD

**Issue by gml16** [MountRouke/DerkGymIssues#1]
Running the "Getting started" code (step 2) of the main page https://gym.derkgame.com/ gives me the following error:

```
[W:pyppeteer.chromium_downloader] start chromium download.
Download may take a few minutes.
100%|████████████████████████████████████████████████████████████████████████████| 218/218 [00:00<00:00, 217342.11it/s]
[W:pyppeteer.chromium_downloader]
chromium download done.
Traceback (most recent call last):
  File ".\main.py", line 3, in <module>
    env = DerkEnv(
  File "C:\Users\gmler\AppData\Local\Programs\Python\Python37\lib\site-packages\gym_derk\envs\derk_env.py", line 86, in __init__
    asyncio.get_event_loop().run_until_complete(self._async_init_game())
  File "C:\Users\gmler\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "C:\Users\gmler\AppData\Local\Programs\Python\Python37\lib\site-packages\gym_derk\envs\derk_env.py", line 156, in _async_init_game
    defaultViewport=None
  File "C:\Users\gmler\AppData\Local\Programs\Python\Python37\lib\site-packages\pyppeteer\launcher.py", line 305, in launch
    return await Launcher(options, **kwargs).launch()
  File "C:\Users\gmler\AppData\Local\Programs\Python\Python37\lib\site-packages\pyppeteer\launcher.py", line 119, in __init__
    download_chromium()
  File "C:\Users\gmler\AppData\Local\Programs\Python\Python37\lib\site-packages\pyppeteer\chromium_downloader.py", line 146, in download_chromium
    extract_zip(download_zip(get_url()), DOWNLOADS_FOLDER / REVISION)
  File "C:\Users\gmler\AppData\Local\Programs\Python\Python37\lib\site-packages\pyppeteer\chromium_downloader.py", line 134, in extract_zip
    with ZipFile(data) as zf:
  File "C:\Users\gmler\AppData\Local\Programs\Python\Python37\lib\zipfile.py", line 1225, in __init__
    self._RealGetContents()
  File "C:\Users\gmler\AppData\Local\Programs\Python\Python37\lib\zipfile.py", line 1292, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

Any suggestion on how to fix this?

(On a side note, there is a typo on the 3rd line of the example code, a comma is missing: `mode='train',` ).

Thanks a lot for your help.

**Comment by FredrikNoren** [comment]
Hi!

I think I've found the problem. Can you try upgrading to gym-derk 0.3.16?

(Also deploying fix for example code. Thanks!)

**Comment by gml16** [comment]
It works, fantastic.
Thanks a lot for your prompt fix.

**Comment by FredrikNoren** [comment]
Great! Thanks for reporting
